version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    image: postgres:15.2
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    build: ../frontend/
    volumes:
      - static:/static
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "10000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/static/api/docs/
      - static:/static
      - media:/media