# Generated by Django 4.2.4 on 2023-08-13 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Цвет тега', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Цвет должен быть в формате "#RRGGBB".', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Идентифифкатор тега', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug может содержать только латинские буквы, цифры, дефисы и подчеркивания.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Идентификатор'),
        ),
    ]
