# Generated by Django 4.2.4 on 2023-08-16 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_color_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть больше 0.'), django.core.validators.MaxValueValidator(1000, message='Слишком большое количество.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1, message='Время готовки должно быть больше 0.'), django.core.validators.MaxValueValidator(1440, message='Слишком большое время готовки.')], verbose_name='Время приготовления'),
        ),
    ]
