# Generated by Django 4.2.4 on 2023-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipes', 'user'), name='unique_favorites_for_recipes'),
        ),
    ]
